my_string = input("Введите любой текст: ")
print("Введено символов: ",len(my_string ))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ','_'))
print('Первый символ строки -',my_string[0])
print('Последний символ строки -',my_string[len(my_string)-1])